// Mocks generated by Mockito 5.4.6 from annotations
// in medicalarm/test/features/medications/medicine_tile_schedule_row_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:medicalarm/entity/group_member_notification_settings.dart' as _i9;
import 'package:medicalarm/entity/medication_history.dart' as _i3;
import 'package:medicalarm/entity/medicine.dart' as _i8;
import 'package:medicalarm/features/resolver/database.dart' as _i2;
import 'package:medicalarm/provider/medication_history.dart' as _i5;
import 'package:medicalarm/utils/local_notification/client.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:riverpod/riverpod.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGroupDatabase_0 extends _i1.SmartFake implements _i2.GroupDatabase {
  _FakeGroupDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMedicationHistory_1 extends _i1.SmartFake implements _i3.MedicationHistory {
  _FakeMedicationHistory_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRef_2<State extends Object?> extends _i1.SmartFake implements _i4.Ref<State> {
  _FakeRef_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MedicationHistoryTake].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationHistoryTake extends _i1.Mock implements _i5.MedicationHistoryTake {
  @override
  _i2.GroupDatabase get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeGroupDatabase_0(
          this,
          Invocation.getter(#database),
        ),
        returnValueForMissingStub: _FakeGroupDatabase_0(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.GroupDatabase);

  @override
  String get userID => (super.noSuchMethod(
        Invocation.getter(#userID),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#userID),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#userID),
        ),
      ) as String);

  @override
  _i7.Future<_i3.MedicationHistory> call({
    required _i3.MedicationHistory? medicationHistory,
    required DateTime? recordedDateTime,
    required DateTime? scheduledRecordedDate,
    required _i8.Medicine? medicine,
    required _i8.MedicationSchedule? medicationSchedule,
    required _i9.GroupMemberNotificationSettings? memberSettings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #medicationHistory: medicationHistory,
            #recordedDateTime: recordedDateTime,
            #scheduledRecordedDate: scheduledRecordedDate,
            #medicine: medicine,
            #medicationSchedule: medicationSchedule,
            #memberSettings: memberSettings,
          },
        ),
        returnValue: _i7.Future<_i3.MedicationHistory>.value(_FakeMedicationHistory_1(
          this,
          Invocation.method(
            #call,
            [],
            {
              #medicationHistory: medicationHistory,
              #recordedDateTime: recordedDateTime,
              #scheduledRecordedDate: scheduledRecordedDate,
              #medicine: medicine,
              #medicationSchedule: medicationSchedule,
              #memberSettings: memberSettings,
            },
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i3.MedicationHistory>.value(_FakeMedicationHistory_1(
          this,
          Invocation.method(
            #call,
            [],
            {
              #medicationHistory: medicationHistory,
              #recordedDateTime: recordedDateTime,
              #scheduledRecordedDate: scheduledRecordedDate,
              #medicine: medicine,
              #medicationSchedule: medicationSchedule,
              #memberSettings: memberSettings,
            },
          ),
        )),
      ) as _i7.Future<_i3.MedicationHistory>);
}

/// A class which mocks [MedicationHistoryDelete].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationHistoryDelete extends _i1.Mock implements _i5.MedicationHistoryDelete {
  @override
  _i2.GroupDatabase get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeGroupDatabase_0(
          this,
          Invocation.getter(#database),
        ),
        returnValueForMissingStub: _FakeGroupDatabase_0(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.GroupDatabase);

  @override
  _i7.Future<void> call(_i3.MedicationHistory? medicationHistory) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [medicationHistory],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [RegisterReminderLocalNotification].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterReminderLocalNotification extends _i1.Mock implements _i10.RegisterReminderLocalNotification {
  @override
  _i4.Ref<Object?> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeRef_2<Object?>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub: _FakeRef_2<Object?>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i4.Ref<Object?>);

  @override
  _i7.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
