// Mocks generated by Mockito 5.4.6 from annotations
// in medicalarm/test/provider/diary_post_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:medicalarm/entity/diary.dart' as _i9;
import 'package:medicalarm/entity/dose_receiver.dart' as _i7;
import 'package:medicalarm/entity/group.dart' as _i5;
import 'package:medicalarm/entity/group_member_notification_settings.dart' as _i11;
import 'package:medicalarm/entity/group_user_profile.dart' as _i10;
import 'package:medicalarm/entity/medication_history.dart' as _i8;
import 'package:medicalarm/entity/medicine.dart' as _i6;
import 'package:medicalarm/features/resolver/database.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDocumentReference_0<T extends Object?> extends _i1.SmartFake implements _i2.DocumentReference<T> {
  _FakeDocumentReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionReference_1<T extends Object?> extends _i1.SmartFake implements _i2.CollectionReference<T> {
  _FakeCollectionReference_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_2 extends _i1.SmartFake implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentSnapshot_3<T extends Object?> extends _i1.SmartFake implements _i2.DocumentSnapshot<T> {
  _FakeDocumentSnapshot_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GroupDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupDatabase extends _i1.Mock implements _i3.GroupDatabase {
  @override
  String get groupID => (super.noSuchMethod(
        Invocation.getter(#groupID),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#groupID),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#groupID),
        ),
      ) as String);

  @override
  _i2.DocumentReference<_i5.Group> groupReference() => (super.noSuchMethod(
        Invocation.method(
          #groupReference,
          [],
        ),
        returnValue: _FakeDocumentReference_0<_i5.Group>(
          this,
          Invocation.method(
            #groupReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i5.Group>(
          this,
          Invocation.method(
            #groupReference,
            [],
          ),
        ),
      ) as _i2.DocumentReference<_i5.Group>);

  @override
  _i2.CollectionReference<_i6.Medicine> medicinesReference() => (super.noSuchMethod(
        Invocation.method(
          #medicinesReference,
          [],
        ),
        returnValue: _FakeCollectionReference_1<_i6.Medicine>(
          this,
          Invocation.method(
            #medicinesReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i6.Medicine>(
          this,
          Invocation.method(
            #medicinesReference,
            [],
          ),
        ),
      ) as _i2.CollectionReference<_i6.Medicine>);

  @override
  _i2.DocumentReference<_i6.Medicine> medicineReference({required String? medicineID}) => (super.noSuchMethod(
        Invocation.method(
          #medicineReference,
          [],
          {#medicineID: medicineID},
        ),
        returnValue: _FakeDocumentReference_0<_i6.Medicine>(
          this,
          Invocation.method(
            #medicineReference,
            [],
            {#medicineID: medicineID},
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i6.Medicine>(
          this,
          Invocation.method(
            #medicineReference,
            [],
            {#medicineID: medicineID},
          ),
        ),
      ) as _i2.DocumentReference<_i6.Medicine>);

  @override
  _i2.CollectionReference<_i7.DoseReceiver> doseReceiversReference() => (super.noSuchMethod(
        Invocation.method(
          #doseReceiversReference,
          [],
        ),
        returnValue: _FakeCollectionReference_1<_i7.DoseReceiver>(
          this,
          Invocation.method(
            #doseReceiversReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i7.DoseReceiver>(
          this,
          Invocation.method(
            #doseReceiversReference,
            [],
          ),
        ),
      ) as _i2.CollectionReference<_i7.DoseReceiver>);

  @override
  _i2.DocumentReference<_i7.DoseReceiver> doseReceiverReference({required String? doseReceiverID}) => (super.noSuchMethod(
        Invocation.method(
          #doseReceiverReference,
          [],
          {#doseReceiverID: doseReceiverID},
        ),
        returnValue: _FakeDocumentReference_0<_i7.DoseReceiver>(
          this,
          Invocation.method(
            #doseReceiverReference,
            [],
            {#doseReceiverID: doseReceiverID},
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i7.DoseReceiver>(
          this,
          Invocation.method(
            #doseReceiverReference,
            [],
            {#doseReceiverID: doseReceiverID},
          ),
        ),
      ) as _i2.DocumentReference<_i7.DoseReceiver>);

  @override
  _i2.CollectionReference<_i8.MedicationHistory> medicationHistoriesReference() => (super.noSuchMethod(
        Invocation.method(
          #medicationHistoriesReference,
          [],
        ),
        returnValue: _FakeCollectionReference_1<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #medicationHistoriesReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #medicationHistoriesReference,
            [],
          ),
        ),
      ) as _i2.CollectionReference<_i8.MedicationHistory>);

  @override
  _i2.CollectionReference<_i9.Diary> diariesReference() => (super.noSuchMethod(
        Invocation.method(
          #diariesReference,
          [],
        ),
        returnValue: _FakeCollectionReference_1<_i9.Diary>(
          this,
          Invocation.method(
            #diariesReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i9.Diary>(
          this,
          Invocation.method(
            #diariesReference,
            [],
          ),
        ),
      ) as _i2.CollectionReference<_i9.Diary>);

  @override
  _i2.DocumentReference<_i9.Diary> diaryReference({required String? diaryID}) => (super.noSuchMethod(
        Invocation.method(
          #diaryReference,
          [],
          {#diaryID: diaryID},
        ),
        returnValue: _FakeDocumentReference_0<_i9.Diary>(
          this,
          Invocation.method(
            #diaryReference,
            [],
            {#diaryID: diaryID},
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i9.Diary>(
          this,
          Invocation.method(
            #diaryReference,
            [],
            {#diaryID: diaryID},
          ),
        ),
      ) as _i2.DocumentReference<_i9.Diary>);

  @override
  _i2.CollectionReference<_i10.GroupUserProfile> userProfilesReference() => (super.noSuchMethod(
        Invocation.method(
          #userProfilesReference,
          [],
        ),
        returnValue: _FakeCollectionReference_1<_i10.GroupUserProfile>(
          this,
          Invocation.method(
            #userProfilesReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i10.GroupUserProfile>(
          this,
          Invocation.method(
            #userProfilesReference,
            [],
          ),
        ),
      ) as _i2.CollectionReference<_i10.GroupUserProfile>);

  @override
  _i2.DocumentReference<_i10.GroupUserProfile> userProfileReference({required String? userID}) => (super.noSuchMethod(
        Invocation.method(
          #userProfileReference,
          [],
          {#userID: userID},
        ),
        returnValue: _FakeDocumentReference_0<_i10.GroupUserProfile>(
          this,
          Invocation.method(
            #userProfileReference,
            [],
            {#userID: userID},
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i10.GroupUserProfile>(
          this,
          Invocation.method(
            #userProfileReference,
            [],
            {#userID: userID},
          ),
        ),
      ) as _i2.DocumentReference<_i10.GroupUserProfile>);

  @override
  _i2.DocumentReference<_i11.GroupMemberNotificationSettings> memberNotificationSettingsReference({required String? userID}) => (super.noSuchMethod(
        Invocation.method(
          #memberNotificationSettingsReference,
          [],
          {#userID: userID},
        ),
        returnValue: _FakeDocumentReference_0<_i11.GroupMemberNotificationSettings>(
          this,
          Invocation.method(
            #memberNotificationSettingsReference,
            [],
            {#userID: userID},
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i11.GroupMemberNotificationSettings>(
          this,
          Invocation.method(
            #memberNotificationSettingsReference,
            [],
            {#userID: userID},
          ),
        ),
      ) as _i2.DocumentReference<_i11.GroupMemberNotificationSettings>);
}

/// A class which mocks [DocumentReference].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockDiaryDocumentReference extends _i1.Mock implements _i2.DocumentReference<_i9.Diary> {
  @override
  _i2.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_2(
          this,
          Invocation.getter(#firestore),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_2(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i2.FirebaseFirestore);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i2.CollectionReference<_i9.Diary> get parent => (super.noSuchMethod(
        Invocation.getter(#parent),
        returnValue: _FakeCollectionReference_1<_i9.Diary>(
          this,
          Invocation.getter(#parent),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i9.Diary>(
          this,
          Invocation.getter(#parent),
        ),
      ) as _i2.CollectionReference<_i9.Diary>);

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  _i2.CollectionReference<Map<String, dynamic>> collection(String? collectionPath) => (super.noSuchMethod(
        Invocation.method(
          #collection,
          [collectionPath],
        ),
        returnValue: _FakeCollectionReference_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collection,
            [collectionPath],
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collection,
            [collectionPath],
          ),
        ),
      ) as _i2.CollectionReference<Map<String, dynamic>>);

  @override
  _i12.Future<void> delete() => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> update(Map<Object, Object?>? data) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [data],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<_i2.DocumentSnapshot<_i9.Diary>> get([_i2.GetOptions? options]) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [options],
        ),
        returnValue: _i12.Future<_i2.DocumentSnapshot<_i9.Diary>>.value(_FakeDocumentSnapshot_3<_i9.Diary>(
          this,
          Invocation.method(
            #get,
            [options],
          ),
        )),
        returnValueForMissingStub: _i12.Future<_i2.DocumentSnapshot<_i9.Diary>>.value(_FakeDocumentSnapshot_3<_i9.Diary>(
          this,
          Invocation.method(
            #get,
            [options],
          ),
        )),
      ) as _i12.Future<_i2.DocumentSnapshot<_i9.Diary>>);

  @override
  _i12.Stream<_i2.DocumentSnapshot<_i9.Diary>> snapshots({
    bool? includeMetadataChanges = false,
    _i2.ListenSource? source = _i2.ListenSource.defaultSource,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #snapshots,
          [],
          {
            #includeMetadataChanges: includeMetadataChanges,
            #source: source,
          },
        ),
        returnValue: _i12.Stream<_i2.DocumentSnapshot<_i9.Diary>>.empty(),
        returnValueForMissingStub: _i12.Stream<_i2.DocumentSnapshot<_i9.Diary>>.empty(),
      ) as _i12.Stream<_i2.DocumentSnapshot<_i9.Diary>>);

  @override
  _i12.Future<void> set(
    _i9.Diary? data, [
    _i2.SetOptions? options,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            data,
            options,
          ],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i2.DocumentReference<R> withConverter<R>({
    required _i2.FromFirestore<R>? fromFirestore,
    required _i2.ToFirestore<R>? toFirestore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #withConverter,
          [],
          {
            #fromFirestore: fromFirestore,
            #toFirestore: toFirestore,
          },
        ),
        returnValue: _FakeDocumentReference_0<R>(
          this,
          Invocation.method(
            #withConverter,
            [],
            {
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            },
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<R>(
          this,
          Invocation.method(
            #withConverter,
            [],
            {
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            },
          ),
        ),
      ) as _i2.DocumentReference<R>);
}
