// Mocks generated by Mockito 5.4.6 from annotations
// in medicalarm/test/provider/dose_receiver_add_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i14;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_core/firebase_core.dart' as _i3;
import 'package:medicalarm/entity/diary.dart' as _i11;
import 'package:medicalarm/entity/dose_receiver.dart' as _i9;
import 'package:medicalarm/entity/group.dart' as _i7;
import 'package:medicalarm/entity/group_member_notification_settings.dart'
    as _i13;
import 'package:medicalarm/entity/group_user_profile.dart' as _i12;
import 'package:medicalarm/entity/medication_history.dart' as _i10;
import 'package:medicalarm/entity/medicine.dart' as _i8;
import 'package:medicalarm/features/resolver/database.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDocumentReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionReference_1<T extends Object?> extends _i1.SmartFake
    implements _i2.CollectionReference<T> {
  _FakeCollectionReference_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_2 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuery_3<T extends Object?> extends _i1.SmartFake
    implements _i2.Query<T> {
  _FakeQuery_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuerySnapshot_4<T extends Object?> extends _i1.SmartFake
    implements _i2.QuerySnapshot<T> {
  _FakeQuerySnapshot_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAggregateQuery_5 extends _i1.SmartFake
    implements _i2.AggregateQuery {
  _FakeAggregateQuery_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentSnapshot_6<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentSnapshot<T> {
  _FakeDocumentSnapshot_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSnapshotMetadata_7 extends _i1.SmartFake
    implements _i2.SnapshotMetadata {
  _FakeSnapshotMetadata_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseApp_8 extends _i1.SmartFake implements _i3.FirebaseApp {
  _FakeFirebaseApp_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettings_9 extends _i1.SmartFake implements _i2.Settings {
  _FakeSettings_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWriteBatch_10 extends _i1.SmartFake implements _i2.WriteBatch {
  _FakeWriteBatch_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoadBundleTask_11 extends _i1.SmartFake
    implements _i2.LoadBundleTask {
  _FakeLoadBundleTask_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_12<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransaction_13 extends _i1.SmartFake implements _i2.Transaction {
  _FakeTransaction_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GroupDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupDatabase extends _i1.Mock implements _i5.GroupDatabase {
  @override
  String get groupID => (super.noSuchMethod(
        Invocation.getter(#groupID),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#groupID),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#groupID),
        ),
      ) as String);

  @override
  _i2.DocumentReference<_i7.Group> groupReference() => (super.noSuchMethod(
        Invocation.method(
          #groupReference,
          [],
        ),
        returnValue: _FakeDocumentReference_0<_i7.Group>(
          this,
          Invocation.method(
            #groupReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i7.Group>(
          this,
          Invocation.method(
            #groupReference,
            [],
          ),
        ),
      ) as _i2.DocumentReference<_i7.Group>);

  @override
  _i2.CollectionReference<_i8.Medicine> medicinesReference() =>
      (super.noSuchMethod(
        Invocation.method(
          #medicinesReference,
          [],
        ),
        returnValue: _FakeCollectionReference_1<_i8.Medicine>(
          this,
          Invocation.method(
            #medicinesReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i8.Medicine>(
          this,
          Invocation.method(
            #medicinesReference,
            [],
          ),
        ),
      ) as _i2.CollectionReference<_i8.Medicine>);

  @override
  _i2.DocumentReference<_i8.Medicine> medicineReference(
          {required String? medicineID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #medicineReference,
          [],
          {#medicineID: medicineID},
        ),
        returnValue: _FakeDocumentReference_0<_i8.Medicine>(
          this,
          Invocation.method(
            #medicineReference,
            [],
            {#medicineID: medicineID},
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i8.Medicine>(
          this,
          Invocation.method(
            #medicineReference,
            [],
            {#medicineID: medicineID},
          ),
        ),
      ) as _i2.DocumentReference<_i8.Medicine>);

  @override
  _i2.CollectionReference<_i9.DoseReceiver> doseReceiversReference() =>
      (super.noSuchMethod(
        Invocation.method(
          #doseReceiversReference,
          [],
        ),
        returnValue: _FakeCollectionReference_1<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #doseReceiversReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #doseReceiversReference,
            [],
          ),
        ),
      ) as _i2.CollectionReference<_i9.DoseReceiver>);

  @override
  _i2.DocumentReference<_i9.DoseReceiver> doseReceiverReference(
          {required String? doseReceiverID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #doseReceiverReference,
          [],
          {#doseReceiverID: doseReceiverID},
        ),
        returnValue: _FakeDocumentReference_0<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #doseReceiverReference,
            [],
            {#doseReceiverID: doseReceiverID},
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #doseReceiverReference,
            [],
            {#doseReceiverID: doseReceiverID},
          ),
        ),
      ) as _i2.DocumentReference<_i9.DoseReceiver>);

  @override
  _i2.CollectionReference<_i10.MedicationHistory>
      medicationHistoriesReference() => (super.noSuchMethod(
            Invocation.method(
              #medicationHistoriesReference,
              [],
            ),
            returnValue: _FakeCollectionReference_1<_i10.MedicationHistory>(
              this,
              Invocation.method(
                #medicationHistoriesReference,
                [],
              ),
            ),
            returnValueForMissingStub:
                _FakeCollectionReference_1<_i10.MedicationHistory>(
              this,
              Invocation.method(
                #medicationHistoriesReference,
                [],
              ),
            ),
          ) as _i2.CollectionReference<_i10.MedicationHistory>);

  @override
  _i2.CollectionReference<_i11.Diary> diariesReference() => (super.noSuchMethod(
        Invocation.method(
          #diariesReference,
          [],
        ),
        returnValue: _FakeCollectionReference_1<_i11.Diary>(
          this,
          Invocation.method(
            #diariesReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i11.Diary>(
          this,
          Invocation.method(
            #diariesReference,
            [],
          ),
        ),
      ) as _i2.CollectionReference<_i11.Diary>);

  @override
  _i2.DocumentReference<_i11.Diary> diaryReference(
          {required String? diaryID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #diaryReference,
          [],
          {#diaryID: diaryID},
        ),
        returnValue: _FakeDocumentReference_0<_i11.Diary>(
          this,
          Invocation.method(
            #diaryReference,
            [],
            {#diaryID: diaryID},
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i11.Diary>(
          this,
          Invocation.method(
            #diaryReference,
            [],
            {#diaryID: diaryID},
          ),
        ),
      ) as _i2.DocumentReference<_i11.Diary>);

  @override
  _i2.CollectionReference<_i12.GroupUserProfile> userProfilesReference() =>
      (super.noSuchMethod(
        Invocation.method(
          #userProfilesReference,
          [],
        ),
        returnValue: _FakeCollectionReference_1<_i12.GroupUserProfile>(
          this,
          Invocation.method(
            #userProfilesReference,
            [],
          ),
        ),
        returnValueForMissingStub:
            _FakeCollectionReference_1<_i12.GroupUserProfile>(
          this,
          Invocation.method(
            #userProfilesReference,
            [],
          ),
        ),
      ) as _i2.CollectionReference<_i12.GroupUserProfile>);

  @override
  _i2.DocumentReference<_i12.GroupUserProfile> userProfileReference(
          {required String? userID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #userProfileReference,
          [],
          {#userID: userID},
        ),
        returnValue: _FakeDocumentReference_0<_i12.GroupUserProfile>(
          this,
          Invocation.method(
            #userProfileReference,
            [],
            {#userID: userID},
          ),
        ),
        returnValueForMissingStub:
            _FakeDocumentReference_0<_i12.GroupUserProfile>(
          this,
          Invocation.method(
            #userProfileReference,
            [],
            {#userID: userID},
          ),
        ),
      ) as _i2.DocumentReference<_i12.GroupUserProfile>);

  @override
  _i2.DocumentReference<_i13.GroupMemberNotificationSettings>
      memberNotificationSettingsReference({required String? userID}) =>
          (super.noSuchMethod(
            Invocation.method(
              #memberNotificationSettingsReference,
              [],
              {#userID: userID},
            ),
            returnValue:
                _FakeDocumentReference_0<_i13.GroupMemberNotificationSettings>(
              this,
              Invocation.method(
                #memberNotificationSettingsReference,
                [],
                {#userID: userID},
              ),
            ),
            returnValueForMissingStub:
                _FakeDocumentReference_0<_i13.GroupMemberNotificationSettings>(
              this,
              Invocation.method(
                #memberNotificationSettingsReference,
                [],
                {#userID: userID},
              ),
            ),
          ) as _i2.DocumentReference<_i13.GroupMemberNotificationSettings>);
}

/// A class which mocks [CollectionReference].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockDoseReceiverCollectionReference extends _i1.Mock
    implements _i2.CollectionReference<_i9.DoseReceiver> {
  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  _i2.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_2(
          this,
          Invocation.getter(#firestore),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_2(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i2.FirebaseFirestore);

  @override
  Map<String, dynamic> get parameters => (super.noSuchMethod(
        Invocation.getter(#parameters),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<_i2.DocumentReference<_i9.DoseReceiver>> add(
          _i9.DoseReceiver? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [data],
        ),
        returnValue: _i4.Future<_i2.DocumentReference<_i9.DoseReceiver>>.value(
            _FakeDocumentReference_0<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #add,
            [data],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.DocumentReference<_i9.DoseReceiver>>.value(
                _FakeDocumentReference_0<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #add,
            [data],
          ),
        )),
      ) as _i4.Future<_i2.DocumentReference<_i9.DoseReceiver>>);

  @override
  _i2.DocumentReference<_i9.DoseReceiver> doc([String? path]) =>
      (super.noSuchMethod(
        Invocation.method(
          #doc,
          [path],
        ),
        returnValue: _FakeDocumentReference_0<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #doc,
            [path],
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #doc,
            [path],
          ),
        ),
      ) as _i2.DocumentReference<_i9.DoseReceiver>);

  @override
  _i2.CollectionReference<R> withConverter<R extends Object?>({
    required _i2.FromFirestore<R>? fromFirestore,
    required _i2.ToFirestore<R>? toFirestore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #withConverter,
          [],
          {
            #fromFirestore: fromFirestore,
            #toFirestore: toFirestore,
          },
        ),
        returnValue: _FakeCollectionReference_1<R>(
          this,
          Invocation.method(
            #withConverter,
            [],
            {
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            },
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<R>(
          this,
          Invocation.method(
            #withConverter,
            [],
            {
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            },
          ),
        ),
      ) as _i2.CollectionReference<R>);

  @override
  _i2.Query<_i9.DoseReceiver> endAtDocument(
          _i2.DocumentSnapshot<Object?>? documentSnapshot) =>
      (super.noSuchMethod(
        Invocation.method(
          #endAtDocument,
          [documentSnapshot],
        ),
        returnValue: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #endAtDocument,
            [documentSnapshot],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #endAtDocument,
            [documentSnapshot],
          ),
        ),
      ) as _i2.Query<_i9.DoseReceiver>);

  @override
  _i2.Query<_i9.DoseReceiver> endAt(Iterable<Object?>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #endAt,
          [values],
        ),
        returnValue: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #endAt,
            [values],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #endAt,
            [values],
          ),
        ),
      ) as _i2.Query<_i9.DoseReceiver>);

  @override
  _i2.Query<_i9.DoseReceiver> endBeforeDocument(
          _i2.DocumentSnapshot<Object?>? documentSnapshot) =>
      (super.noSuchMethod(
        Invocation.method(
          #endBeforeDocument,
          [documentSnapshot],
        ),
        returnValue: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #endBeforeDocument,
            [documentSnapshot],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #endBeforeDocument,
            [documentSnapshot],
          ),
        ),
      ) as _i2.Query<_i9.DoseReceiver>);

  @override
  _i2.Query<_i9.DoseReceiver> endBefore(Iterable<Object?>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #endBefore,
          [values],
        ),
        returnValue: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #endBefore,
            [values],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #endBefore,
            [values],
          ),
        ),
      ) as _i2.Query<_i9.DoseReceiver>);

  @override
  _i4.Future<_i2.QuerySnapshot<_i9.DoseReceiver>> get(
          [_i2.GetOptions? options]) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [options],
        ),
        returnValue: _i4.Future<_i2.QuerySnapshot<_i9.DoseReceiver>>.value(
            _FakeQuerySnapshot_4<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #get,
            [options],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.QuerySnapshot<_i9.DoseReceiver>>.value(
                _FakeQuerySnapshot_4<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #get,
            [options],
          ),
        )),
      ) as _i4.Future<_i2.QuerySnapshot<_i9.DoseReceiver>>);

  @override
  _i2.Query<_i9.DoseReceiver> limit(int? limit) => (super.noSuchMethod(
        Invocation.method(
          #limit,
          [limit],
        ),
        returnValue: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #limit,
            [limit],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #limit,
            [limit],
          ),
        ),
      ) as _i2.Query<_i9.DoseReceiver>);

  @override
  _i2.Query<_i9.DoseReceiver> limitToLast(int? limit) => (super.noSuchMethod(
        Invocation.method(
          #limitToLast,
          [limit],
        ),
        returnValue: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #limitToLast,
            [limit],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #limitToLast,
            [limit],
          ),
        ),
      ) as _i2.Query<_i9.DoseReceiver>);

  @override
  _i4.Stream<_i2.QuerySnapshot<_i9.DoseReceiver>> snapshots({
    bool? includeMetadataChanges = false,
    _i2.ListenSource? source = _i2.ListenSource.defaultSource,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #snapshots,
          [],
          {
            #includeMetadataChanges: includeMetadataChanges,
            #source: source,
          },
        ),
        returnValue: _i4.Stream<_i2.QuerySnapshot<_i9.DoseReceiver>>.empty(),
        returnValueForMissingStub:
            _i4.Stream<_i2.QuerySnapshot<_i9.DoseReceiver>>.empty(),
      ) as _i4.Stream<_i2.QuerySnapshot<_i9.DoseReceiver>>);

  @override
  _i2.Query<_i9.DoseReceiver> orderBy(
    Object? field, {
    bool? descending = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #orderBy,
          [field],
          {#descending: descending},
        ),
        returnValue: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #orderBy,
            [field],
            {#descending: descending},
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #orderBy,
            [field],
            {#descending: descending},
          ),
        ),
      ) as _i2.Query<_i9.DoseReceiver>);

  @override
  _i2.Query<_i9.DoseReceiver> startAfterDocument(
          _i2.DocumentSnapshot<Object?>? documentSnapshot) =>
      (super.noSuchMethod(
        Invocation.method(
          #startAfterDocument,
          [documentSnapshot],
        ),
        returnValue: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #startAfterDocument,
            [documentSnapshot],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #startAfterDocument,
            [documentSnapshot],
          ),
        ),
      ) as _i2.Query<_i9.DoseReceiver>);

  @override
  _i2.Query<_i9.DoseReceiver> startAfter(Iterable<Object?>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #startAfter,
          [values],
        ),
        returnValue: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #startAfter,
            [values],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #startAfter,
            [values],
          ),
        ),
      ) as _i2.Query<_i9.DoseReceiver>);

  @override
  _i2.Query<_i9.DoseReceiver> startAtDocument(
          _i2.DocumentSnapshot<Object?>? documentSnapshot) =>
      (super.noSuchMethod(
        Invocation.method(
          #startAtDocument,
          [documentSnapshot],
        ),
        returnValue: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #startAtDocument,
            [documentSnapshot],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #startAtDocument,
            [documentSnapshot],
          ),
        ),
      ) as _i2.Query<_i9.DoseReceiver>);

  @override
  _i2.Query<_i9.DoseReceiver> startAt(Iterable<Object?>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #startAt,
          [values],
        ),
        returnValue: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #startAt,
            [values],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #startAt,
            [values],
          ),
        ),
      ) as _i2.Query<_i9.DoseReceiver>);

  @override
  _i2.Query<_i9.DoseReceiver> where(
    Object? field, {
    Object? isEqualTo,
    Object? isNotEqualTo,
    Object? isLessThan,
    Object? isLessThanOrEqualTo,
    Object? isGreaterThan,
    Object? isGreaterThanOrEqualTo,
    Object? arrayContains,
    Iterable<Object?>? arrayContainsAny,
    Iterable<Object?>? whereIn,
    Iterable<Object?>? whereNotIn,
    bool? isNull,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #where,
          [field],
          {
            #isEqualTo: isEqualTo,
            #isNotEqualTo: isNotEqualTo,
            #isLessThan: isLessThan,
            #isLessThanOrEqualTo: isLessThanOrEqualTo,
            #isGreaterThan: isGreaterThan,
            #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
            #arrayContains: arrayContains,
            #arrayContainsAny: arrayContainsAny,
            #whereIn: whereIn,
            #whereNotIn: whereNotIn,
            #isNull: isNull,
          },
        ),
        returnValue: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #where,
            [field],
            {
              #isEqualTo: isEqualTo,
              #isNotEqualTo: isNotEqualTo,
              #isLessThan: isLessThan,
              #isLessThanOrEqualTo: isLessThanOrEqualTo,
              #isGreaterThan: isGreaterThan,
              #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
              #arrayContains: arrayContains,
              #arrayContainsAny: arrayContainsAny,
              #whereIn: whereIn,
              #whereNotIn: whereNotIn,
              #isNull: isNull,
            },
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #where,
            [field],
            {
              #isEqualTo: isEqualTo,
              #isNotEqualTo: isNotEqualTo,
              #isLessThan: isLessThan,
              #isLessThanOrEqualTo: isLessThanOrEqualTo,
              #isGreaterThan: isGreaterThan,
              #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
              #arrayContains: arrayContains,
              #arrayContainsAny: arrayContainsAny,
              #whereIn: whereIn,
              #whereNotIn: whereNotIn,
              #isNull: isNull,
            },
          ),
        ),
      ) as _i2.Query<_i9.DoseReceiver>);

  @override
  _i2.AggregateQuery count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _FakeAggregateQuery_5(
          this,
          Invocation.method(
            #count,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeAggregateQuery_5(
          this,
          Invocation.method(
            #count,
            [],
          ),
        ),
      ) as _i2.AggregateQuery);

  @override
  _i2.AggregateQuery aggregate(
    _i2.AggregateField? aggregateField1, [
    _i2.AggregateField? aggregateField2,
    _i2.AggregateField? aggregateField3,
    _i2.AggregateField? aggregateField4,
    _i2.AggregateField? aggregateField5,
    _i2.AggregateField? aggregateField6,
    _i2.AggregateField? aggregateField7,
    _i2.AggregateField? aggregateField8,
    _i2.AggregateField? aggregateField9,
    _i2.AggregateField? aggregateField10,
    _i2.AggregateField? aggregateField11,
    _i2.AggregateField? aggregateField12,
    _i2.AggregateField? aggregateField13,
    _i2.AggregateField? aggregateField14,
    _i2.AggregateField? aggregateField15,
    _i2.AggregateField? aggregateField16,
    _i2.AggregateField? aggregateField17,
    _i2.AggregateField? aggregateField18,
    _i2.AggregateField? aggregateField19,
    _i2.AggregateField? aggregateField20,
    _i2.AggregateField? aggregateField21,
    _i2.AggregateField? aggregateField22,
    _i2.AggregateField? aggregateField23,
    _i2.AggregateField? aggregateField24,
    _i2.AggregateField? aggregateField25,
    _i2.AggregateField? aggregateField26,
    _i2.AggregateField? aggregateField27,
    _i2.AggregateField? aggregateField28,
    _i2.AggregateField? aggregateField29,
    _i2.AggregateField? aggregateField30,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #aggregate,
          [
            aggregateField1,
            aggregateField2,
            aggregateField3,
            aggregateField4,
            aggregateField5,
            aggregateField6,
            aggregateField7,
            aggregateField8,
            aggregateField9,
            aggregateField10,
            aggregateField11,
            aggregateField12,
            aggregateField13,
            aggregateField14,
            aggregateField15,
            aggregateField16,
            aggregateField17,
            aggregateField18,
            aggregateField19,
            aggregateField20,
            aggregateField21,
            aggregateField22,
            aggregateField23,
            aggregateField24,
            aggregateField25,
            aggregateField26,
            aggregateField27,
            aggregateField28,
            aggregateField29,
            aggregateField30,
          ],
        ),
        returnValue: _FakeAggregateQuery_5(
          this,
          Invocation.method(
            #aggregate,
            [
              aggregateField1,
              aggregateField2,
              aggregateField3,
              aggregateField4,
              aggregateField5,
              aggregateField6,
              aggregateField7,
              aggregateField8,
              aggregateField9,
              aggregateField10,
              aggregateField11,
              aggregateField12,
              aggregateField13,
              aggregateField14,
              aggregateField15,
              aggregateField16,
              aggregateField17,
              aggregateField18,
              aggregateField19,
              aggregateField20,
              aggregateField21,
              aggregateField22,
              aggregateField23,
              aggregateField24,
              aggregateField25,
              aggregateField26,
              aggregateField27,
              aggregateField28,
              aggregateField29,
              aggregateField30,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeAggregateQuery_5(
          this,
          Invocation.method(
            #aggregate,
            [
              aggregateField1,
              aggregateField2,
              aggregateField3,
              aggregateField4,
              aggregateField5,
              aggregateField6,
              aggregateField7,
              aggregateField8,
              aggregateField9,
              aggregateField10,
              aggregateField11,
              aggregateField12,
              aggregateField13,
              aggregateField14,
              aggregateField15,
              aggregateField16,
              aggregateField17,
              aggregateField18,
              aggregateField19,
              aggregateField20,
              aggregateField21,
              aggregateField22,
              aggregateField23,
              aggregateField24,
              aggregateField25,
              aggregateField26,
              aggregateField27,
              aggregateField28,
              aggregateField29,
              aggregateField30,
            ],
          ),
        ),
      ) as _i2.AggregateQuery);
}

/// A class which mocks [DocumentReference].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockDoseReceiverDocumentReference extends _i1.Mock
    implements _i2.DocumentReference<_i9.DoseReceiver> {
  @override
  _i2.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_2(
          this,
          Invocation.getter(#firestore),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_2(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i2.FirebaseFirestore);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i2.CollectionReference<_i9.DoseReceiver> get parent => (super.noSuchMethod(
        Invocation.getter(#parent),
        returnValue: _FakeCollectionReference_1<_i9.DoseReceiver>(
          this,
          Invocation.getter(#parent),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i9.DoseReceiver>(
          this,
          Invocation.getter(#parent),
        ),
      ) as _i2.CollectionReference<_i9.DoseReceiver>);

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  _i2.CollectionReference<Map<String, dynamic>> collection(
          String? collectionPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #collection,
          [collectionPath],
        ),
        returnValue: _FakeCollectionReference_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collection,
            [collectionPath],
          ),
        ),
        returnValueForMissingStub:
            _FakeCollectionReference_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collection,
            [collectionPath],
          ),
        ),
      ) as _i2.CollectionReference<Map<String, dynamic>>);

  @override
  _i4.Future<void> delete() => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> update(Map<Object, Object?>? data) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [data],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.DocumentSnapshot<_i9.DoseReceiver>> get(
          [_i2.GetOptions? options]) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [options],
        ),
        returnValue: _i4.Future<_i2.DocumentSnapshot<_i9.DoseReceiver>>.value(
            _FakeDocumentSnapshot_6<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #get,
            [options],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.DocumentSnapshot<_i9.DoseReceiver>>.value(
                _FakeDocumentSnapshot_6<_i9.DoseReceiver>(
          this,
          Invocation.method(
            #get,
            [options],
          ),
        )),
      ) as _i4.Future<_i2.DocumentSnapshot<_i9.DoseReceiver>>);

  @override
  _i4.Stream<_i2.DocumentSnapshot<_i9.DoseReceiver>> snapshots({
    bool? includeMetadataChanges = false,
    _i2.ListenSource? source = _i2.ListenSource.defaultSource,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #snapshots,
          [],
          {
            #includeMetadataChanges: includeMetadataChanges,
            #source: source,
          },
        ),
        returnValue: _i4.Stream<_i2.DocumentSnapshot<_i9.DoseReceiver>>.empty(),
        returnValueForMissingStub:
            _i4.Stream<_i2.DocumentSnapshot<_i9.DoseReceiver>>.empty(),
      ) as _i4.Stream<_i2.DocumentSnapshot<_i9.DoseReceiver>>);

  @override
  _i4.Future<void> set(
    _i9.DoseReceiver? data, [
    _i2.SetOptions? options,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            data,
            options,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.DocumentReference<R> withConverter<R>({
    required _i2.FromFirestore<R>? fromFirestore,
    required _i2.ToFirestore<R>? toFirestore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #withConverter,
          [],
          {
            #fromFirestore: fromFirestore,
            #toFirestore: toFirestore,
          },
        ),
        returnValue: _FakeDocumentReference_0<R>(
          this,
          Invocation.method(
            #withConverter,
            [],
            {
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            },
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<R>(
          this,
          Invocation.method(
            #withConverter,
            [],
            {
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            },
          ),
        ),
      ) as _i2.DocumentReference<R>);
}

/// A class which mocks [DocumentSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoseReceiverDocumentSnapshot extends _i1.Mock
    implements _i2.DocumentSnapshot<_i9.DoseReceiver> {
  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i2.DocumentReference<_i9.DoseReceiver> get reference => (super.noSuchMethod(
        Invocation.getter(#reference),
        returnValue: _FakeDocumentReference_0<_i9.DoseReceiver>(
          this,
          Invocation.getter(#reference),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i9.DoseReceiver>(
          this,
          Invocation.getter(#reference),
        ),
      ) as _i2.DocumentReference<_i9.DoseReceiver>);

  @override
  _i2.SnapshotMetadata get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakeSnapshotMetadata_7(
          this,
          Invocation.getter(#metadata),
        ),
        returnValueForMissingStub: _FakeSnapshotMetadata_7(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i2.SnapshotMetadata);

  @override
  bool get exists => (super.noSuchMethod(
        Invocation.getter(#exists),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  dynamic get(Object? field) => super.noSuchMethod(
        Invocation.method(
          #get,
          [field],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic operator [](Object? field) => super.noSuchMethod(
        Invocation.method(
          #[],
          [field],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FirebaseFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestore extends _i1.Mock implements _i2.FirebaseFirestore {
  @override
  _i3.FirebaseApp get app => (super.noSuchMethod(
        Invocation.getter(#app),
        returnValue: _FakeFirebaseApp_8(
          this,
          Invocation.getter(#app),
        ),
        returnValueForMissingStub: _FakeFirebaseApp_8(
          this,
          Invocation.getter(#app),
        ),
      ) as _i3.FirebaseApp);

  @override
  String get databaseId => (super.noSuchMethod(
        Invocation.getter(#databaseId),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#databaseId),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#databaseId),
        ),
      ) as String);

  @override
  _i2.Settings get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeSettings_9(
          this,
          Invocation.getter(#settings),
        ),
        returnValueForMissingStub: _FakeSettings_9(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i2.Settings);

  @override
  set app(_i3.FirebaseApp? _app) => super.noSuchMethod(
        Invocation.setter(
          #app,
          _app,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set databaseId(String? _databaseId) => super.noSuchMethod(
        Invocation.setter(
          #databaseId,
          _databaseId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set settings(_i2.Settings? settings) => super.noSuchMethod(
        Invocation.setter(
          #settings,
          settings,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<dynamic, dynamic> get pluginConstants => (super.noSuchMethod(
        Invocation.getter(#pluginConstants),
        returnValue: <dynamic, dynamic>{},
        returnValueForMissingStub: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);

  @override
  _i2.CollectionReference<Map<String, dynamic>> collection(
          String? collectionPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #collection,
          [collectionPath],
        ),
        returnValue: _FakeCollectionReference_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collection,
            [collectionPath],
          ),
        ),
        returnValueForMissingStub:
            _FakeCollectionReference_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collection,
            [collectionPath],
          ),
        ),
      ) as _i2.CollectionReference<Map<String, dynamic>>);

  @override
  _i2.WriteBatch batch() => (super.noSuchMethod(
        Invocation.method(
          #batch,
          [],
        ),
        returnValue: _FakeWriteBatch_10(
          this,
          Invocation.method(
            #batch,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeWriteBatch_10(
          this,
          Invocation.method(
            #batch,
            [],
          ),
        ),
      ) as _i2.WriteBatch);

  @override
  _i4.Future<void> clearPersistence() => (super.noSuchMethod(
        Invocation.method(
          #clearPersistence,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.LoadBundleTask loadBundle(_i14.Uint8List? bundle) => (super.noSuchMethod(
        Invocation.method(
          #loadBundle,
          [bundle],
        ),
        returnValue: _FakeLoadBundleTask_11(
          this,
          Invocation.method(
            #loadBundle,
            [bundle],
          ),
        ),
        returnValueForMissingStub: _FakeLoadBundleTask_11(
          this,
          Invocation.method(
            #loadBundle,
            [bundle],
          ),
        ),
      ) as _i2.LoadBundleTask);

  @override
  void useFirestoreEmulator(
    String? host,
    int? port, {
    bool? sslEnabled = false,
    bool? automaticHostMapping = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #useFirestoreEmulator,
          [
            host,
            port,
          ],
          {
            #sslEnabled: sslEnabled,
            #automaticHostMapping: automaticHostMapping,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i2.QuerySnapshot<T>> namedQueryWithConverterGet<T>(
    String? name, {
    _i2.GetOptions? options = const _i2.GetOptions(),
    required _i2.FromFirestore<T>? fromFirestore,
    required _i2.ToFirestore<T>? toFirestore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #namedQueryWithConverterGet,
          [name],
          {
            #options: options,
            #fromFirestore: fromFirestore,
            #toFirestore: toFirestore,
          },
        ),
        returnValue:
            _i4.Future<_i2.QuerySnapshot<T>>.value(_FakeQuerySnapshot_4<T>(
          this,
          Invocation.method(
            #namedQueryWithConverterGet,
            [name],
            {
              #options: options,
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.QuerySnapshot<T>>.value(_FakeQuerySnapshot_4<T>(
          this,
          Invocation.method(
            #namedQueryWithConverterGet,
            [name],
            {
              #options: options,
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            },
          ),
        )),
      ) as _i4.Future<_i2.QuerySnapshot<T>>);

  @override
  _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>> namedQueryGet(
    String? name, {
    _i2.GetOptions? options = const _i2.GetOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #namedQueryGet,
          [name],
          {#options: options},
        ),
        returnValue: _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
            _FakeQuerySnapshot_4<Map<String, dynamic>>(
          this,
          Invocation.method(
            #namedQueryGet,
            [name],
            {#options: options},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                _FakeQuerySnapshot_4<Map<String, dynamic>>(
          this,
          Invocation.method(
            #namedQueryGet,
            [name],
            {#options: options},
          ),
        )),
      ) as _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i2.Query<Map<String, dynamic>> collectionGroup(String? collectionPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #collectionGroup,
          [collectionPath],
        ),
        returnValue: _FakeQuery_3<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collectionGroup,
            [collectionPath],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collectionGroup,
            [collectionPath],
          ),
        ),
      ) as _i2.Query<Map<String, dynamic>>);

  @override
  _i4.Future<void> disableNetwork() => (super.noSuchMethod(
        Invocation.method(
          #disableNetwork,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.DocumentReference<Map<String, dynamic>> doc(String? documentPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #doc,
          [documentPath],
        ),
        returnValue: _FakeDocumentReference_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #doc,
            [documentPath],
          ),
        ),
        returnValueForMissingStub:
            _FakeDocumentReference_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #doc,
            [documentPath],
          ),
        ),
      ) as _i2.DocumentReference<Map<String, dynamic>>);

  @override
  _i4.Future<void> enableNetwork() => (super.noSuchMethod(
        Invocation.method(
          #enableNetwork,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<void> snapshotsInSync() => (super.noSuchMethod(
        Invocation.method(
          #snapshotsInSync,
          [],
        ),
        returnValue: _i4.Stream<void>.empty(),
        returnValueForMissingStub: _i4.Stream<void>.empty(),
      ) as _i4.Stream<void>);

  @override
  _i4.Future<T> runTransaction<T>(
    _i2.TransactionHandler<T>? transactionHandler, {
    Duration? timeout = const Duration(seconds: 30),
    int? maxAttempts = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runTransaction,
          [transactionHandler],
          {
            #timeout: timeout,
            #maxAttempts: maxAttempts,
          },
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #runTransaction,
                  [transactionHandler],
                  {
                    #timeout: timeout,
                    #maxAttempts: maxAttempts,
                  },
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_12<T>(
              this,
              Invocation.method(
                #runTransaction,
                [transactionHandler],
                {
                  #timeout: timeout,
                  #maxAttempts: maxAttempts,
                },
              ),
            ),
        returnValueForMissingStub: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #runTransaction,
                  [transactionHandler],
                  {
                    #timeout: timeout,
                    #maxAttempts: maxAttempts,
                  },
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_12<T>(
              this,
              Invocation.method(
                #runTransaction,
                [transactionHandler],
                {
                  #timeout: timeout,
                  #maxAttempts: maxAttempts,
                },
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<void> terminate() => (super.noSuchMethod(
        Invocation.method(
          #terminate,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> waitForPendingWrites() => (super.noSuchMethod(
        Invocation.method(
          #waitForPendingWrites,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setIndexConfigurationFromJSON(String? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #setIndexConfigurationFromJSON,
          [json],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [Transaction].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransaction extends _i1.Mock implements _i2.Transaction {
  @override
  _i4.Future<_i2.DocumentSnapshot<T>> get<T extends Object?>(
          _i2.DocumentReference<T>? documentReference) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [documentReference],
        ),
        returnValue: _i4.Future<_i2.DocumentSnapshot<T>>.value(
            _FakeDocumentSnapshot_6<T>(
          this,
          Invocation.method(
            #get,
            [documentReference],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.DocumentSnapshot<T>>.value(
            _FakeDocumentSnapshot_6<T>(
          this,
          Invocation.method(
            #get,
            [documentReference],
          ),
        )),
      ) as _i4.Future<_i2.DocumentSnapshot<T>>);

  @override
  _i2.Transaction delete(_i2.DocumentReference<Object?>? documentReference) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [documentReference],
        ),
        returnValue: _FakeTransaction_13(
          this,
          Invocation.method(
            #delete,
            [documentReference],
          ),
        ),
        returnValueForMissingStub: _FakeTransaction_13(
          this,
          Invocation.method(
            #delete,
            [documentReference],
          ),
        ),
      ) as _i2.Transaction);

  @override
  _i2.Transaction update(
    _i2.DocumentReference<Object?>? documentReference,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            documentReference,
            data,
          ],
        ),
        returnValue: _FakeTransaction_13(
          this,
          Invocation.method(
            #update,
            [
              documentReference,
              data,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeTransaction_13(
          this,
          Invocation.method(
            #update,
            [
              documentReference,
              data,
            ],
          ),
        ),
      ) as _i2.Transaction);

  @override
  _i2.Transaction set<T>(
    _i2.DocumentReference<T>? documentReference,
    T? data, [
    _i2.SetOptions? options,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            documentReference,
            data,
            options,
          ],
        ),
        returnValue: _FakeTransaction_13(
          this,
          Invocation.method(
            #set,
            [
              documentReference,
              data,
              options,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeTransaction_13(
          this,
          Invocation.method(
            #set,
            [
              documentReference,
              data,
              options,
            ],
          ),
        ),
      ) as _i2.Transaction);
}
