// Mocks generated by Mockito 5.4.6 from annotations
// in medicalarm/test/provider/medication_history_revert_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:medicalarm/entity/diary.dart' as _i9;
import 'package:medicalarm/entity/dose_receiver.dart' as _i7;
import 'package:medicalarm/entity/group.dart' as _i5;
import 'package:medicalarm/entity/group_member_notification_settings.dart' as _i11;
import 'package:medicalarm/entity/group_user_profile.dart' as _i10;
import 'package:medicalarm/entity/medication_history.dart' as _i8;
import 'package:medicalarm/entity/medicine.dart' as _i6;
import 'package:medicalarm/features/resolver/database.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDocumentReference_0<T extends Object?> extends _i1.SmartFake implements _i2.DocumentReference<T> {
  _FakeDocumentReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionReference_1<T extends Object?> extends _i1.SmartFake implements _i2.CollectionReference<T> {
  _FakeCollectionReference_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_2 extends _i1.SmartFake implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuery_3<T extends Object?> extends _i1.SmartFake implements _i2.Query<T> {
  _FakeQuery_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuerySnapshot_4<T extends Object?> extends _i1.SmartFake implements _i2.QuerySnapshot<T> {
  _FakeQuerySnapshot_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAggregateQuery_5 extends _i1.SmartFake implements _i2.AggregateQuery {
  _FakeAggregateQuery_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentSnapshot_6<T extends Object?> extends _i1.SmartFake implements _i2.DocumentSnapshot<T> {
  _FakeDocumentSnapshot_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GroupDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupDatabase extends _i1.Mock implements _i3.GroupDatabase {
  @override
  String get groupID => (super.noSuchMethod(
        Invocation.getter(#groupID),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#groupID),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#groupID),
        ),
      ) as String);

  @override
  _i2.DocumentReference<_i5.Group> groupReference() => (super.noSuchMethod(
        Invocation.method(
          #groupReference,
          [],
        ),
        returnValue: _FakeDocumentReference_0<_i5.Group>(
          this,
          Invocation.method(
            #groupReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i5.Group>(
          this,
          Invocation.method(
            #groupReference,
            [],
          ),
        ),
      ) as _i2.DocumentReference<_i5.Group>);

  @override
  _i2.CollectionReference<_i6.Medicine> medicinesReference() => (super.noSuchMethod(
        Invocation.method(
          #medicinesReference,
          [],
        ),
        returnValue: _FakeCollectionReference_1<_i6.Medicine>(
          this,
          Invocation.method(
            #medicinesReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i6.Medicine>(
          this,
          Invocation.method(
            #medicinesReference,
            [],
          ),
        ),
      ) as _i2.CollectionReference<_i6.Medicine>);

  @override
  _i2.DocumentReference<_i6.Medicine> medicineReference({required String? medicineID}) => (super.noSuchMethod(
        Invocation.method(
          #medicineReference,
          [],
          {#medicineID: medicineID},
        ),
        returnValue: _FakeDocumentReference_0<_i6.Medicine>(
          this,
          Invocation.method(
            #medicineReference,
            [],
            {#medicineID: medicineID},
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i6.Medicine>(
          this,
          Invocation.method(
            #medicineReference,
            [],
            {#medicineID: medicineID},
          ),
        ),
      ) as _i2.DocumentReference<_i6.Medicine>);

  @override
  _i2.CollectionReference<_i7.DoseReceiver> doseReceiversReference() => (super.noSuchMethod(
        Invocation.method(
          #doseReceiversReference,
          [],
        ),
        returnValue: _FakeCollectionReference_1<_i7.DoseReceiver>(
          this,
          Invocation.method(
            #doseReceiversReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i7.DoseReceiver>(
          this,
          Invocation.method(
            #doseReceiversReference,
            [],
          ),
        ),
      ) as _i2.CollectionReference<_i7.DoseReceiver>);

  @override
  _i2.DocumentReference<_i7.DoseReceiver> doseReceiverReference({required String? doseReceiverID}) => (super.noSuchMethod(
        Invocation.method(
          #doseReceiverReference,
          [],
          {#doseReceiverID: doseReceiverID},
        ),
        returnValue: _FakeDocumentReference_0<_i7.DoseReceiver>(
          this,
          Invocation.method(
            #doseReceiverReference,
            [],
            {#doseReceiverID: doseReceiverID},
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i7.DoseReceiver>(
          this,
          Invocation.method(
            #doseReceiverReference,
            [],
            {#doseReceiverID: doseReceiverID},
          ),
        ),
      ) as _i2.DocumentReference<_i7.DoseReceiver>);

  @override
  _i2.CollectionReference<_i8.MedicationHistory> medicationHistoriesReference() => (super.noSuchMethod(
        Invocation.method(
          #medicationHistoriesReference,
          [],
        ),
        returnValue: _FakeCollectionReference_1<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #medicationHistoriesReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #medicationHistoriesReference,
            [],
          ),
        ),
      ) as _i2.CollectionReference<_i8.MedicationHistory>);

  @override
  _i2.CollectionReference<_i9.Diary> diariesReference() => (super.noSuchMethod(
        Invocation.method(
          #diariesReference,
          [],
        ),
        returnValue: _FakeCollectionReference_1<_i9.Diary>(
          this,
          Invocation.method(
            #diariesReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i9.Diary>(
          this,
          Invocation.method(
            #diariesReference,
            [],
          ),
        ),
      ) as _i2.CollectionReference<_i9.Diary>);

  @override
  _i2.DocumentReference<_i9.Diary> diaryReference({required String? diaryID}) => (super.noSuchMethod(
        Invocation.method(
          #diaryReference,
          [],
          {#diaryID: diaryID},
        ),
        returnValue: _FakeDocumentReference_0<_i9.Diary>(
          this,
          Invocation.method(
            #diaryReference,
            [],
            {#diaryID: diaryID},
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i9.Diary>(
          this,
          Invocation.method(
            #diaryReference,
            [],
            {#diaryID: diaryID},
          ),
        ),
      ) as _i2.DocumentReference<_i9.Diary>);

  @override
  _i2.CollectionReference<_i10.GroupUserProfile> userProfilesReference() => (super.noSuchMethod(
        Invocation.method(
          #userProfilesReference,
          [],
        ),
        returnValue: _FakeCollectionReference_1<_i10.GroupUserProfile>(
          this,
          Invocation.method(
            #userProfilesReference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i10.GroupUserProfile>(
          this,
          Invocation.method(
            #userProfilesReference,
            [],
          ),
        ),
      ) as _i2.CollectionReference<_i10.GroupUserProfile>);

  @override
  _i2.DocumentReference<_i10.GroupUserProfile> userProfileReference({required String? userID}) => (super.noSuchMethod(
        Invocation.method(
          #userProfileReference,
          [],
          {#userID: userID},
        ),
        returnValue: _FakeDocumentReference_0<_i10.GroupUserProfile>(
          this,
          Invocation.method(
            #userProfileReference,
            [],
            {#userID: userID},
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i10.GroupUserProfile>(
          this,
          Invocation.method(
            #userProfileReference,
            [],
            {#userID: userID},
          ),
        ),
      ) as _i2.DocumentReference<_i10.GroupUserProfile>);

  @override
  _i2.DocumentReference<_i11.GroupMemberNotificationSettings> memberNotificationSettingsReference({required String? userID}) => (super.noSuchMethod(
        Invocation.method(
          #memberNotificationSettingsReference,
          [],
          {#userID: userID},
        ),
        returnValue: _FakeDocumentReference_0<_i11.GroupMemberNotificationSettings>(
          this,
          Invocation.method(
            #memberNotificationSettingsReference,
            [],
            {#userID: userID},
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i11.GroupMemberNotificationSettings>(
          this,
          Invocation.method(
            #memberNotificationSettingsReference,
            [],
            {#userID: userID},
          ),
        ),
      ) as _i2.DocumentReference<_i11.GroupMemberNotificationSettings>);
}

/// A class which mocks [CollectionReference].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockMedicationHistoryCollectionReference extends _i1.Mock implements _i2.CollectionReference<_i8.MedicationHistory> {
  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  _i2.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_2(
          this,
          Invocation.getter(#firestore),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_2(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i2.FirebaseFirestore);

  @override
  Map<String, dynamic> get parameters => (super.noSuchMethod(
        Invocation.getter(#parameters),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i12.Future<_i2.DocumentReference<_i8.MedicationHistory>> add(_i8.MedicationHistory? data) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [data],
        ),
        returnValue: _i12.Future<_i2.DocumentReference<_i8.MedicationHistory>>.value(_FakeDocumentReference_0<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #add,
            [data],
          ),
        )),
        returnValueForMissingStub: _i12.Future<_i2.DocumentReference<_i8.MedicationHistory>>.value(_FakeDocumentReference_0<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #add,
            [data],
          ),
        )),
      ) as _i12.Future<_i2.DocumentReference<_i8.MedicationHistory>>);

  @override
  _i2.DocumentReference<_i8.MedicationHistory> doc([String? path]) => (super.noSuchMethod(
        Invocation.method(
          #doc,
          [path],
        ),
        returnValue: _FakeDocumentReference_0<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #doc,
            [path],
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #doc,
            [path],
          ),
        ),
      ) as _i2.DocumentReference<_i8.MedicationHistory>);

  @override
  _i2.CollectionReference<R> withConverter<R extends Object?>({
    required _i2.FromFirestore<R>? fromFirestore,
    required _i2.ToFirestore<R>? toFirestore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #withConverter,
          [],
          {
            #fromFirestore: fromFirestore,
            #toFirestore: toFirestore,
          },
        ),
        returnValue: _FakeCollectionReference_1<R>(
          this,
          Invocation.method(
            #withConverter,
            [],
            {
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            },
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<R>(
          this,
          Invocation.method(
            #withConverter,
            [],
            {
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            },
          ),
        ),
      ) as _i2.CollectionReference<R>);

  @override
  _i2.Query<_i8.MedicationHistory> endAtDocument(_i2.DocumentSnapshot<Object?>? documentSnapshot) => (super.noSuchMethod(
        Invocation.method(
          #endAtDocument,
          [documentSnapshot],
        ),
        returnValue: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #endAtDocument,
            [documentSnapshot],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #endAtDocument,
            [documentSnapshot],
          ),
        ),
      ) as _i2.Query<_i8.MedicationHistory>);

  @override
  _i2.Query<_i8.MedicationHistory> endAt(Iterable<Object?>? values) => (super.noSuchMethod(
        Invocation.method(
          #endAt,
          [values],
        ),
        returnValue: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #endAt,
            [values],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #endAt,
            [values],
          ),
        ),
      ) as _i2.Query<_i8.MedicationHistory>);

  @override
  _i2.Query<_i8.MedicationHistory> endBeforeDocument(_i2.DocumentSnapshot<Object?>? documentSnapshot) => (super.noSuchMethod(
        Invocation.method(
          #endBeforeDocument,
          [documentSnapshot],
        ),
        returnValue: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #endBeforeDocument,
            [documentSnapshot],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #endBeforeDocument,
            [documentSnapshot],
          ),
        ),
      ) as _i2.Query<_i8.MedicationHistory>);

  @override
  _i2.Query<_i8.MedicationHistory> endBefore(Iterable<Object?>? values) => (super.noSuchMethod(
        Invocation.method(
          #endBefore,
          [values],
        ),
        returnValue: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #endBefore,
            [values],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #endBefore,
            [values],
          ),
        ),
      ) as _i2.Query<_i8.MedicationHistory>);

  @override
  _i12.Future<_i2.QuerySnapshot<_i8.MedicationHistory>> get([_i2.GetOptions? options]) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [options],
        ),
        returnValue: _i12.Future<_i2.QuerySnapshot<_i8.MedicationHistory>>.value(_FakeQuerySnapshot_4<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #get,
            [options],
          ),
        )),
        returnValueForMissingStub: _i12.Future<_i2.QuerySnapshot<_i8.MedicationHistory>>.value(_FakeQuerySnapshot_4<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #get,
            [options],
          ),
        )),
      ) as _i12.Future<_i2.QuerySnapshot<_i8.MedicationHistory>>);

  @override
  _i2.Query<_i8.MedicationHistory> limit(int? limit) => (super.noSuchMethod(
        Invocation.method(
          #limit,
          [limit],
        ),
        returnValue: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #limit,
            [limit],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #limit,
            [limit],
          ),
        ),
      ) as _i2.Query<_i8.MedicationHistory>);

  @override
  _i2.Query<_i8.MedicationHistory> limitToLast(int? limit) => (super.noSuchMethod(
        Invocation.method(
          #limitToLast,
          [limit],
        ),
        returnValue: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #limitToLast,
            [limit],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #limitToLast,
            [limit],
          ),
        ),
      ) as _i2.Query<_i8.MedicationHistory>);

  @override
  _i12.Stream<_i2.QuerySnapshot<_i8.MedicationHistory>> snapshots({
    bool? includeMetadataChanges = false,
    _i2.ListenSource? source = _i2.ListenSource.defaultSource,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #snapshots,
          [],
          {
            #includeMetadataChanges: includeMetadataChanges,
            #source: source,
          },
        ),
        returnValue: _i12.Stream<_i2.QuerySnapshot<_i8.MedicationHistory>>.empty(),
        returnValueForMissingStub: _i12.Stream<_i2.QuerySnapshot<_i8.MedicationHistory>>.empty(),
      ) as _i12.Stream<_i2.QuerySnapshot<_i8.MedicationHistory>>);

  @override
  _i2.Query<_i8.MedicationHistory> orderBy(
    Object? field, {
    bool? descending = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #orderBy,
          [field],
          {#descending: descending},
        ),
        returnValue: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #orderBy,
            [field],
            {#descending: descending},
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #orderBy,
            [field],
            {#descending: descending},
          ),
        ),
      ) as _i2.Query<_i8.MedicationHistory>);

  @override
  _i2.Query<_i8.MedicationHistory> startAfterDocument(_i2.DocumentSnapshot<Object?>? documentSnapshot) => (super.noSuchMethod(
        Invocation.method(
          #startAfterDocument,
          [documentSnapshot],
        ),
        returnValue: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #startAfterDocument,
            [documentSnapshot],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #startAfterDocument,
            [documentSnapshot],
          ),
        ),
      ) as _i2.Query<_i8.MedicationHistory>);

  @override
  _i2.Query<_i8.MedicationHistory> startAfter(Iterable<Object?>? values) => (super.noSuchMethod(
        Invocation.method(
          #startAfter,
          [values],
        ),
        returnValue: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #startAfter,
            [values],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #startAfter,
            [values],
          ),
        ),
      ) as _i2.Query<_i8.MedicationHistory>);

  @override
  _i2.Query<_i8.MedicationHistory> startAtDocument(_i2.DocumentSnapshot<Object?>? documentSnapshot) => (super.noSuchMethod(
        Invocation.method(
          #startAtDocument,
          [documentSnapshot],
        ),
        returnValue: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #startAtDocument,
            [documentSnapshot],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #startAtDocument,
            [documentSnapshot],
          ),
        ),
      ) as _i2.Query<_i8.MedicationHistory>);

  @override
  _i2.Query<_i8.MedicationHistory> startAt(Iterable<Object?>? values) => (super.noSuchMethod(
        Invocation.method(
          #startAt,
          [values],
        ),
        returnValue: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #startAt,
            [values],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #startAt,
            [values],
          ),
        ),
      ) as _i2.Query<_i8.MedicationHistory>);

  @override
  _i2.Query<_i8.MedicationHistory> where(
    Object? field, {
    Object? isEqualTo,
    Object? isNotEqualTo,
    Object? isLessThan,
    Object? isLessThanOrEqualTo,
    Object? isGreaterThan,
    Object? isGreaterThanOrEqualTo,
    Object? arrayContains,
    Iterable<Object?>? arrayContainsAny,
    Iterable<Object?>? whereIn,
    Iterable<Object?>? whereNotIn,
    bool? isNull,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #where,
          [field],
          {
            #isEqualTo: isEqualTo,
            #isNotEqualTo: isNotEqualTo,
            #isLessThan: isLessThan,
            #isLessThanOrEqualTo: isLessThanOrEqualTo,
            #isGreaterThan: isGreaterThan,
            #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
            #arrayContains: arrayContains,
            #arrayContainsAny: arrayContainsAny,
            #whereIn: whereIn,
            #whereNotIn: whereNotIn,
            #isNull: isNull,
          },
        ),
        returnValue: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #where,
            [field],
            {
              #isEqualTo: isEqualTo,
              #isNotEqualTo: isNotEqualTo,
              #isLessThan: isLessThan,
              #isLessThanOrEqualTo: isLessThanOrEqualTo,
              #isGreaterThan: isGreaterThan,
              #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
              #arrayContains: arrayContains,
              #arrayContainsAny: arrayContainsAny,
              #whereIn: whereIn,
              #whereNotIn: whereNotIn,
              #isNull: isNull,
            },
          ),
        ),
        returnValueForMissingStub: _FakeQuery_3<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #where,
            [field],
            {
              #isEqualTo: isEqualTo,
              #isNotEqualTo: isNotEqualTo,
              #isLessThan: isLessThan,
              #isLessThanOrEqualTo: isLessThanOrEqualTo,
              #isGreaterThan: isGreaterThan,
              #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
              #arrayContains: arrayContains,
              #arrayContainsAny: arrayContainsAny,
              #whereIn: whereIn,
              #whereNotIn: whereNotIn,
              #isNull: isNull,
            },
          ),
        ),
      ) as _i2.Query<_i8.MedicationHistory>);

  @override
  _i2.AggregateQuery count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _FakeAggregateQuery_5(
          this,
          Invocation.method(
            #count,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeAggregateQuery_5(
          this,
          Invocation.method(
            #count,
            [],
          ),
        ),
      ) as _i2.AggregateQuery);

  @override
  _i2.AggregateQuery aggregate(
    _i2.AggregateField? aggregateField1, [
    _i2.AggregateField? aggregateField2,
    _i2.AggregateField? aggregateField3,
    _i2.AggregateField? aggregateField4,
    _i2.AggregateField? aggregateField5,
    _i2.AggregateField? aggregateField6,
    _i2.AggregateField? aggregateField7,
    _i2.AggregateField? aggregateField8,
    _i2.AggregateField? aggregateField9,
    _i2.AggregateField? aggregateField10,
    _i2.AggregateField? aggregateField11,
    _i2.AggregateField? aggregateField12,
    _i2.AggregateField? aggregateField13,
    _i2.AggregateField? aggregateField14,
    _i2.AggregateField? aggregateField15,
    _i2.AggregateField? aggregateField16,
    _i2.AggregateField? aggregateField17,
    _i2.AggregateField? aggregateField18,
    _i2.AggregateField? aggregateField19,
    _i2.AggregateField? aggregateField20,
    _i2.AggregateField? aggregateField21,
    _i2.AggregateField? aggregateField22,
    _i2.AggregateField? aggregateField23,
    _i2.AggregateField? aggregateField24,
    _i2.AggregateField? aggregateField25,
    _i2.AggregateField? aggregateField26,
    _i2.AggregateField? aggregateField27,
    _i2.AggregateField? aggregateField28,
    _i2.AggregateField? aggregateField29,
    _i2.AggregateField? aggregateField30,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #aggregate,
          [
            aggregateField1,
            aggregateField2,
            aggregateField3,
            aggregateField4,
            aggregateField5,
            aggregateField6,
            aggregateField7,
            aggregateField8,
            aggregateField9,
            aggregateField10,
            aggregateField11,
            aggregateField12,
            aggregateField13,
            aggregateField14,
            aggregateField15,
            aggregateField16,
            aggregateField17,
            aggregateField18,
            aggregateField19,
            aggregateField20,
            aggregateField21,
            aggregateField22,
            aggregateField23,
            aggregateField24,
            aggregateField25,
            aggregateField26,
            aggregateField27,
            aggregateField28,
            aggregateField29,
            aggregateField30,
          ],
        ),
        returnValue: _FakeAggregateQuery_5(
          this,
          Invocation.method(
            #aggregate,
            [
              aggregateField1,
              aggregateField2,
              aggregateField3,
              aggregateField4,
              aggregateField5,
              aggregateField6,
              aggregateField7,
              aggregateField8,
              aggregateField9,
              aggregateField10,
              aggregateField11,
              aggregateField12,
              aggregateField13,
              aggregateField14,
              aggregateField15,
              aggregateField16,
              aggregateField17,
              aggregateField18,
              aggregateField19,
              aggregateField20,
              aggregateField21,
              aggregateField22,
              aggregateField23,
              aggregateField24,
              aggregateField25,
              aggregateField26,
              aggregateField27,
              aggregateField28,
              aggregateField29,
              aggregateField30,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeAggregateQuery_5(
          this,
          Invocation.method(
            #aggregate,
            [
              aggregateField1,
              aggregateField2,
              aggregateField3,
              aggregateField4,
              aggregateField5,
              aggregateField6,
              aggregateField7,
              aggregateField8,
              aggregateField9,
              aggregateField10,
              aggregateField11,
              aggregateField12,
              aggregateField13,
              aggregateField14,
              aggregateField15,
              aggregateField16,
              aggregateField17,
              aggregateField18,
              aggregateField19,
              aggregateField20,
              aggregateField21,
              aggregateField22,
              aggregateField23,
              aggregateField24,
              aggregateField25,
              aggregateField26,
              aggregateField27,
              aggregateField28,
              aggregateField29,
              aggregateField30,
            ],
          ),
        ),
      ) as _i2.AggregateQuery);
}

/// A class which mocks [DocumentReference].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockMedicationHistoryDocumentReference extends _i1.Mock implements _i2.DocumentReference<_i8.MedicationHistory> {
  @override
  _i2.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_2(
          this,
          Invocation.getter(#firestore),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_2(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i2.FirebaseFirestore);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i2.CollectionReference<_i8.MedicationHistory> get parent => (super.noSuchMethod(
        Invocation.getter(#parent),
        returnValue: _FakeCollectionReference_1<_i8.MedicationHistory>(
          this,
          Invocation.getter(#parent),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<_i8.MedicationHistory>(
          this,
          Invocation.getter(#parent),
        ),
      ) as _i2.CollectionReference<_i8.MedicationHistory>);

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  _i2.CollectionReference<Map<String, dynamic>> collection(String? collectionPath) => (super.noSuchMethod(
        Invocation.method(
          #collection,
          [collectionPath],
        ),
        returnValue: _FakeCollectionReference_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collection,
            [collectionPath],
          ),
        ),
        returnValueForMissingStub: _FakeCollectionReference_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collection,
            [collectionPath],
          ),
        ),
      ) as _i2.CollectionReference<Map<String, dynamic>>);

  @override
  _i12.Future<void> delete() => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> update(Map<Object, Object?>? data) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [data],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<_i2.DocumentSnapshot<_i8.MedicationHistory>> get([_i2.GetOptions? options]) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [options],
        ),
        returnValue: _i12.Future<_i2.DocumentSnapshot<_i8.MedicationHistory>>.value(_FakeDocumentSnapshot_6<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #get,
            [options],
          ),
        )),
        returnValueForMissingStub: _i12.Future<_i2.DocumentSnapshot<_i8.MedicationHistory>>.value(_FakeDocumentSnapshot_6<_i8.MedicationHistory>(
          this,
          Invocation.method(
            #get,
            [options],
          ),
        )),
      ) as _i12.Future<_i2.DocumentSnapshot<_i8.MedicationHistory>>);

  @override
  _i12.Stream<_i2.DocumentSnapshot<_i8.MedicationHistory>> snapshots({
    bool? includeMetadataChanges = false,
    _i2.ListenSource? source = _i2.ListenSource.defaultSource,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #snapshots,
          [],
          {
            #includeMetadataChanges: includeMetadataChanges,
            #source: source,
          },
        ),
        returnValue: _i12.Stream<_i2.DocumentSnapshot<_i8.MedicationHistory>>.empty(),
        returnValueForMissingStub: _i12.Stream<_i2.DocumentSnapshot<_i8.MedicationHistory>>.empty(),
      ) as _i12.Stream<_i2.DocumentSnapshot<_i8.MedicationHistory>>);

  @override
  _i12.Future<void> set(
    _i8.MedicationHistory? data, [
    _i2.SetOptions? options,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            data,
            options,
          ],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i2.DocumentReference<R> withConverter<R>({
    required _i2.FromFirestore<R>? fromFirestore,
    required _i2.ToFirestore<R>? toFirestore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #withConverter,
          [],
          {
            #fromFirestore: fromFirestore,
            #toFirestore: toFirestore,
          },
        ),
        returnValue: _FakeDocumentReference_0<R>(
          this,
          Invocation.method(
            #withConverter,
            [],
            {
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            },
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_0<R>(
          this,
          Invocation.method(
            #withConverter,
            [],
            {
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            },
          ),
        ),
      ) as _i2.DocumentReference<R>);
}
